CREATE TABLE #T1 (COLUNA INT)
INSERT #T1 (COLUNA) SELECT 1
INSERT #T1 (COLUNA) SELECT 2
INSERT #T1 (COLUNA) SELECT 3

CREATE TABLE #T2 (COLUNA INT)
INSERT #T2 (COLUNA) SELECT 3
INSERT #T2 (COLUNA) SELECT 4
INSERT #T2 (COLUNA) SELECT 5

--> COMO ENTENDER OS JOINS DE UMA VEZ POR TODAS
-- INNER JOIN
SELECT A.COLUNA AS 'INFO_T1', B.COLUNA AS 'INFO_T2' 
FROM #T1 A INNER JOIN (SELECT * FROM #T2) B ON A.COLUNA = B.COLUNA
-- JOIN
SELECT * FROM #T1 JOIN #T2 ON #T1.COLUNA = #T2.COLUNA
-- LEFT JOIN
SELECT A.COLUNA AS 'INFO_T1', B.COLUNA AS 'INFO_T2' 
FROM #T1 A LEFT JOIN (SELECT * FROM #T2) B ON A.COLUNA = B.COLUNA
-- RIGHT JOIN
SELECT A.COLUNA AS 'INFO_T1', B.COLUNA AS 'INFO_T2' 
FROM #T1 A RIGHT JOIN (SELECT * FROM #T2) B ON A.COLUNA = B.COLUNA
-- FULL JOIN
SELECT A.COLUNA AS 'INFO_T1', B.COLUNA AS 'INFO_T2' 
FROM #T1 A FULL JOIN (SELECT * FROM #T2) B ON A.COLUNA = B.COLUNA
-- CROSS JOIN
SELECT A.COLUNA AS 'INFO_T1', B.COLUNA AS 'INFO_T2' 
FROM #T1 A CROSS JOIN (SELECT * FROM #T2) B